apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-go
  labels:
    app: sample-go
spec:
  replicas: 5
  template:
    metadata:
      labels:
        run: sample-go
    spec:
      containers:
      - name: sample-go
        image: quay.io/coffeepac/sample-go:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthBad
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 2

---
apiVersion: v1
kind: Service
metadata:
  name: sample-go
  labels:
    app: sample-go
spec:
  ports:
    - port: 8080
  selector:
    app: sample-go
  type: LoadBalancer