apiVersion: v1
kind: Pod
metadata:
  name: sample-go
  labels:
    app: sample-go
  annotations:  
    pod.beta.kubernetes.io/init-containers: '[
      {
        "name": "directory-prep",
        "image": "quay.io/samsung_cnct/shared-logging-directory:0.3",
        "imagePullPolicy": "Always",
        "volumeMounts": [
          {
            "name": "log-pointer",
            "mountPath": "/log-pointer"
          },{
            "name": "logs",
            "mountPath": "/hostlogs"
          }
        ],
        "env": [
          {
            "name": "POD_NAME",
            "valueFrom": {
              "fieldRef": {
		"APIVersion": "v1",
                "fieldPath": "metadata.name"
              }
            }
          },{
            "name": "POD_NAMESPACE",
            "valueFrom": {
              "fieldRef": {
		"APIVersion": "v1",
                "fieldPath": "metadata.namespace"
              }
            }
          },{
            "name": "POD_IP",
            "valueFrom": {
              "fieldRef": {
		"APIVersion": "v1",
                "fieldPath": "status.podIP"
              }
            }
          }
        ]
      }]'
spec:
  containers:
    - name: sample-go
      image: quay.io/coffeepac/sample-go:0.3
      ports:
      - containerPort: 8080
      volumeMounts:
        - name: log-pointer
          mountPath: /var/log/apps
        - name: logs
          mountPath: /hostlogs
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
  volumes:
    - name: logs
      hostPath:
        path: /var/log/containers/clean-location-one  #  common across all pods.  an init pod creates the globally unique directory
    - name: log-pointer
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sample-go
  labels:
    app: sample-go
spec:
  ports:
    - port: 8080
  selector:
    app: sample-go
  type: LoadBalancer
