apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Values.name}}
  labels:
    app: {{.Values.name}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - name: {{.Values.name}}
        image: quay.io/coffeepac/sample-go
        ports:
        - containerPort: {{.Values.httpport}}
        livenessProbe:
          httpGet:
            path: {{.Values.health_path}}
            port: {{.Values.httpport}}
          initialDelaySeconds: {{.Values.health_delay_seconds}}
          timeoutSeconds: {{.Values.health_timeout_seconds}}
---
apiVersion: v1
kind: Service
metadata:
  name: sample-go
  labels:
    app: sample-go
spec:
  ports:
    - port: {{.Values.httpport}}
  selector:
    app: sample-go
  type: LoadBalancer

